### ISSUE TITLE
Question about "max" parameter

### ISSUE THREAD

**Issue by stackola** [ThreeLetters/HashBounds#10]
Hello, 

very useful library you wrote here.

Could you just clarify the use of the "max" parameter in the constructor?

`
var hashBounds = new HashBounds(10,2,100)  // Cell size, levels, max`

Is that the maximum position in both directions? So for a 10.000 x 10.000 map I would use 10.000 (plus the max size of an object?)

If you could clear that up for me I would appreciate it.

**Comment by Andrews54757** [comment]
@stackola Yes, that is the max position for both sides. If you want though, I could change it. Not a biggie

**Comment by Andrews54757** [comment]
@stackola I have created a new branch for you. It allows you to do this:

>new HashBounds(10,2,100,100) // Cell size, levels, maxX, maxY

Also note that cell size is in powers of two


I added these other functions as well: checkBoundsMax(bounds), and truncateBounds(bounds)


checkBoundsMax(bounds) checks whether a certain bound fits. Returns false if it doesnt fit.


truncateBounds(bounds) "truncates" bounds so it makes it fit.


Example:


```js
var hashbounds = new HashBounds(10,2,100,100) // Cell size, levels, maxX, maxY

var bounds = {
x: 90,
y: 60,
width: 20,
height: 30
}

if (hashbounds.checkBoundsMax(bounds)) { // returns false
hashbounds.truncateBounds(bounds);

/*
bounds: {
x: 90,
y: 60,
width: 10,
height: 30
...
}

*/
}
```
