### ISSUE TITLE
Closest unoccupied space?

### ISSUE THREAD

**Issue by fresheneesz** [ThreeLetters/HashBounds#8]
Hi, this may be a little off topic, but this looks like a pretty cool system. I'm curious if it would be easy to add something that could be used to identify the closest unoccupied space (or a "close" heuristic). I don't know anything about how quad trees or spacial hashes work, so this might be kind of a long shot. But this kind of system that adds spacial objects into it and can query them seems like it could be the right place for this kind of functionality.

**Comment by Andrews54757** [comment]
@fresheneesz Yes, you can. Use the hashbounds.every function

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/OpenAgar/blob/master/source/core/main.js#L768

https://github.com/AJS-development/OpenAgar/blob/master/source/core/main.js#L1319

**Comment by fresheneesz** [comment]
@Andrews54757 Not sure I understand. Looks like the `every` method just loops through all nodes within the given bounds in some unspecified order. The code you linked is only a collision checker. I don't see how that would help me find the closest unoccupied space of a certain dimensions.

**Comment by Andrews54757** [comment]
@fresheneesz Well... Finding the closest occupied space is hard. The only way you can do it with this so far, is to pick random locations nearby and check them. I will add it later though.

**Comment by fresheneesz** [comment]
If it was easy I woulda implemented it myself ; ) 

> I will add it later though.

That's great to hear! Do you know what techniques you'll use to implement it?

**Comment by Andrews54757** [comment]
@fresheneesz Not really. Kinda busy on other stuff. Dont know why you would want it though.

**Comment by fresheneesz** [comment]
@Andrews54757 Oh.. it just sounded like said you were planning on doing it...

What I wanted this for is to automatically position tooltips at the same time so they were close to the item on the screen they related to, but don't overlap with any of the other tooltips or the on-screen items they relate to. I wasn't able to find any module that had functionality I could use to implement that.

**Comment by Andrews54757** [comment]
@fresheneesz Css. Use css for that. This library is for handling with tons of items with varying sizes - not for web design.

**Comment by Andrews54757** [comment]
@fresheneesz Yes, I will add nearest neighbor search - but I dont know about nearest unoccupied space.

**Comment by fresheneesz** [comment]
@Andrews54757  I don't think there's any possible way for me to use CSS for this. But if there is in fact a way, I'd love to know. 

Re: Neighbor search - that's great to know! Thanks!
